package com.recommend_system.eduandsalary.entity;

public class EduandSalary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eduandsalary.need_num
     *
     * @mbggenerated
     */
    private Integer needNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eduandsalary.avg_salary
     *
     * @mbggenerated
     */
    private Integer avgSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eduandsalary.education
     *
     * @mbggenerated
     */
    private Integer education;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eduandsalary.need_num
     *
     * @return the value of eduandsalary.need_num
     *
     * @mbggenerated
     */
    public Integer getNeedNum() {
        return needNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eduandsalary.need_num
     *
     * @param needNum the value for eduandsalary.need_num
     *
     * @mbggenerated
     */
    public void setNeedNum(Integer needNum) {
        this.needNum = needNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eduandsalary.avg_salary
     *
     * @return the value of eduandsalary.avg_salary
     *
     * @mbggenerated
     */
    public Integer getAvgSalary() {
        return avgSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eduandsalary.avg_salary
     *
     * @param avgSalary the value for eduandsalary.avg_salary
     *
     * @mbggenerated
     */
    public void setAvgSalary(Integer avgSalary) {
        this.avgSalary = avgSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eduandsalary.education
     *
     * @return the value of eduandsalary.education
     *
     * @mbggenerated
     */
    public Integer getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eduandsalary.education
     *
     * @param education the value for eduandsalary.education
     *
     * @mbggenerated
     */
    public void setEducation(Integer education) {
        this.education = education;
    }
}