package com.recommend_system.citysalary.dao;

import com.recommend_system.citysalary.entity.CitySalary;
import com.recommend_system.citysalary.entity.CitySalaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CitySalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table citysalary
     *
     * @mbggenerated
     */
    int countByExample(CitySalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table citysalary
     *
     * @mbggenerated
     */
    int deleteByExample(CitySalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table citysalary
     *
     * @mbggenerated
     */
    int insert(CitySalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table citysalary
     *
     * @mbggenerated
     */
    int insertSelective(CitySalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table citysalary
     *
     * @mbggenerated
     */
    List<CitySalary> selectByExample(CitySalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table citysalary
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CitySalary record, @Param("example") CitySalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table citysalary
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CitySalary record, @Param("example") CitySalaryExample example);
}