package com.recommend_system.companyindustry.entity;

public class CompanyIndustry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyindustry.company_industry
     *
     * @mbggenerated
     */
    private String companyIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyindustry.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyindustry.company_industry
     *
     * @return the value of companyindustry.company_industry
     *
     * @mbggenerated
     */
    public String getCompanyIndustry() {
        return companyIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyindustry.company_industry
     *
     * @param companyIndustry the value for companyindustry.company_industry
     *
     * @mbggenerated
     */
    public void setCompanyIndustry(String companyIndustry) {
        this.companyIndustry = companyIndustry == null ? null : companyIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyindustry.num
     *
     * @return the value of companyindustry.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyindustry.num
     *
     * @param num the value for companyindustry.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}