package com.recommend_system.citysalary.entity;

public class CitySalary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column citysalary.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column citysalary.avg_salary
     *
     * @mbggenerated
     */
    private Integer avgSalary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column citysalary.city
     *
     * @return the value of citysalary.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column citysalary.city
     *
     * @param city the value for citysalary.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column citysalary.avg_salary
     *
     * @return the value of citysalary.avg_salary
     *
     * @mbggenerated
     */
    public Integer getAvgSalary() {
        return avgSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column citysalary.avg_salary
     *
     * @param avgSalary the value for citysalary.avg_salary
     *
     * @mbggenerated
     */
    public void setAvgSalary(Integer avgSalary) {
        this.avgSalary = avgSalary;
    }
}