package com.recommend_system.expandsalary.dao;

import com.recommend_system.expandsalary.entity.ExpandSalary;
import com.recommend_system.expandsalary.entity.ExpandSalaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpandSalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expandsalary
     *
     * @mbggenerated
     */
    int countByExample(ExpandSalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expandsalary
     *
     * @mbggenerated
     */
    int deleteByExample(ExpandSalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expandsalary
     *
     * @mbggenerated
     */
    int insert(ExpandSalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expandsalary
     *
     * @mbggenerated
     */
    int insertSelective(ExpandSalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expandsalary
     *
     * @mbggenerated
     */
    List<ExpandSalary> selectByExample(ExpandSalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expandsalary
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ExpandSalary record, @Param("example") ExpandSalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expandsalary
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ExpandSalary record, @Param("example") ExpandSalaryExample example);
}