package com.recommend_system.companyscale.dao;

import com.recommend_system.companyscale.entity.CompanyScale;
import com.recommend_system.companyscale.entity.CompanyScaleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyScaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyscale
     *
     * @mbggenerated
     */
    int countByExample(CompanyScaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyscale
     *
     * @mbggenerated
     */
    int deleteByExample(CompanyScaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyscale
     *
     * @mbggenerated
     */
    int insert(CompanyScale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyscale
     *
     * @mbggenerated
     */
    int insertSelective(CompanyScale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyscale
     *
     * @mbggenerated
     */
    List<CompanyScale> selectByExample(CompanyScaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyscale
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CompanyScale record, @Param("example") CompanyScaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyscale
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CompanyScale record, @Param("example") CompanyScaleExample example);
}