package com.recommend_system.cindustrytreat.entity;

import java.util.ArrayList;
import java.util.List;

public class CIndustryTreatExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    public CIndustryTreatExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWorknumIsNull() {
            addCriterion("worknum is null");
            return (Criteria) this;
        }

        public Criteria andWorknumIsNotNull() {
            addCriterion("worknum is not null");
            return (Criteria) this;
        }

        public Criteria andWorknumEqualTo(Integer value) {
            addCriterion("worknum =", value, "worknum");
            return (Criteria) this;
        }

        public Criteria andWorknumNotEqualTo(Integer value) {
            addCriterion("worknum <>", value, "worknum");
            return (Criteria) this;
        }

        public Criteria andWorknumGreaterThan(Integer value) {
            addCriterion("worknum >", value, "worknum");
            return (Criteria) this;
        }

        public Criteria andWorknumGreaterThanOrEqualTo(Integer value) {
            addCriterion("worknum >=", value, "worknum");
            return (Criteria) this;
        }

        public Criteria andWorknumLessThan(Integer value) {
            addCriterion("worknum <", value, "worknum");
            return (Criteria) this;
        }

        public Criteria andWorknumLessThanOrEqualTo(Integer value) {
            addCriterion("worknum <=", value, "worknum");
            return (Criteria) this;
        }

        public Criteria andWorknumIn(List<Integer> values) {
            addCriterion("worknum in", values, "worknum");
            return (Criteria) this;
        }

        public Criteria andWorknumNotIn(List<Integer> values) {
            addCriterion("worknum not in", values, "worknum");
            return (Criteria) this;
        }

        public Criteria andWorknumBetween(Integer value1, Integer value2) {
            addCriterion("worknum between", value1, value2, "worknum");
            return (Criteria) this;
        }

        public Criteria andWorknumNotBetween(Integer value1, Integer value2) {
            addCriterion("worknum not between", value1, value2, "worknum");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryIsNull() {
            addCriterion("company_industry is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryIsNotNull() {
            addCriterion("company_industry is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryEqualTo(String value) {
            addCriterion("company_industry =", value, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryNotEqualTo(String value) {
            addCriterion("company_industry <>", value, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryGreaterThan(String value) {
            addCriterion("company_industry >", value, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryGreaterThanOrEqualTo(String value) {
            addCriterion("company_industry >=", value, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryLessThan(String value) {
            addCriterion("company_industry <", value, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryLessThanOrEqualTo(String value) {
            addCriterion("company_industry <=", value, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryLike(String value) {
            addCriterion("company_industry like", value, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryNotLike(String value) {
            addCriterion("company_industry not like", value, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryIn(List<String> values) {
            addCriterion("company_industry in", values, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryNotIn(List<String> values) {
            addCriterion("company_industry not in", values, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryBetween(String value1, String value2) {
            addCriterion("company_industry between", value1, value2, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andCompanyIndustryNotBetween(String value1, String value2) {
            addCriterion("company_industry not between", value1, value2, "companyIndustry");
            return (Criteria) this;
        }

        public Criteria andAvgSalaryIsNull() {
            addCriterion("avg_salary is null");
            return (Criteria) this;
        }

        public Criteria andAvgSalaryIsNotNull() {
            addCriterion("avg_salary is not null");
            return (Criteria) this;
        }

        public Criteria andAvgSalaryEqualTo(Integer value) {
            addCriterion("avg_salary =", value, "avgSalary");
            return (Criteria) this;
        }

        public Criteria andAvgSalaryNotEqualTo(Integer value) {
            addCriterion("avg_salary <>", value, "avgSalary");
            return (Criteria) this;
        }

        public Criteria andAvgSalaryGreaterThan(Integer value) {
            addCriterion("avg_salary >", value, "avgSalary");
            return (Criteria) this;
        }

        public Criteria andAvgSalaryGreaterThanOrEqualTo(Integer value) {
            addCriterion("avg_salary >=", value, "avgSalary");
            return (Criteria) this;
        }

        public Criteria andAvgSalaryLessThan(Integer value) {
            addCriterion("avg_salary <", value, "avgSalary");
            return (Criteria) this;
        }

        public Criteria andAvgSalaryLessThanOrEqualTo(Integer value) {
            addCriterion("avg_salary <=", value, "avgSalary");
            return (Criteria) this;
        }

        public Criteria andAvgSalaryIn(List<Integer> values) {
            addCriterion("avg_salary in", values, "avgSalary");
            return (Criteria) this;
        }

        public Criteria andAvgSalaryNotIn(List<Integer> values) {
            addCriterion("avg_salary not in", values, "avgSalary");
            return (Criteria) this;
        }

        public Criteria andAvgSalaryBetween(Integer value1, Integer value2) {
            addCriterion("avg_salary between", value1, value2, "avgSalary");
            return (Criteria) this;
        }

        public Criteria andAvgSalaryNotBetween(Integer value1, Integer value2) {
            addCriterion("avg_salary not between", value1, value2, "avgSalary");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cindustry_treat
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}