package com.recommend_system.cindustrytreat.entity;

public class CIndustryTreat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cindustry_treat.worknum
     *
     * @mbggenerated
     */
    private Integer worknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cindustry_treat.company_industry
     *
     * @mbggenerated
     */
    private String companyIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cindustry_treat.avg_salary
     *
     * @mbggenerated
     */
    private Integer avgSalary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cindustry_treat.worknum
     *
     * @return the value of cindustry_treat.worknum
     *
     * @mbggenerated
     */
    public Integer getWorknum() {
        return worknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cindustry_treat.worknum
     *
     * @param worknum the value for cindustry_treat.worknum
     *
     * @mbggenerated
     */
    public void setWorknum(Integer worknum) {
        this.worknum = worknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cindustry_treat.company_industry
     *
     * @return the value of cindustry_treat.company_industry
     *
     * @mbggenerated
     */
    public String getCompanyIndustry() {
        return companyIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cindustry_treat.company_industry
     *
     * @param companyIndustry the value for cindustry_treat.company_industry
     *
     * @mbggenerated
     */
    public void setCompanyIndustry(String companyIndustry) {
        this.companyIndustry = companyIndustry == null ? null : companyIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cindustry_treat.avg_salary
     *
     * @return the value of cindustry_treat.avg_salary
     *
     * @mbggenerated
     */
    public Integer getAvgSalary() {
        return avgSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cindustry_treat.avg_salary
     *
     * @param avgSalary the value for cindustry_treat.avg_salary
     *
     * @mbggenerated
     */
    public void setAvgSalary(Integer avgSalary) {
        this.avgSalary = avgSalary;
    }
}