package com.recommend_system.companyindustry.dao;

import com.recommend_system.companyindustry.entity.CompanyIndustry;
import com.recommend_system.companyindustry.entity.CompanyIndustryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyIndustryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyindustry
     *
     * @mbggenerated
     */
    int countByExample(CompanyIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyindustry
     *
     * @mbggenerated
     */
    int deleteByExample(CompanyIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyindustry
     *
     * @mbggenerated
     */
    int insert(CompanyIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyindustry
     *
     * @mbggenerated
     */
    int insertSelective(CompanyIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyindustry
     *
     * @mbggenerated
     */
    List<CompanyIndustry> selectByExample(CompanyIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyindustry
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CompanyIndustry record, @Param("example") CompanyIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyindustry
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CompanyIndustry record, @Param("example") CompanyIndustryExample example);
}