package com.recommend_system.cnaturetreat.dao;

import com.recommend_system.cnaturetreat.entity.CNatureTreat;
import com.recommend_system.cnaturetreat.entity.CNatureTreatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CNatureTreatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnature_treat
     *
     * @mbggenerated
     */
    int countByExample(CNatureTreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnature_treat
     *
     * @mbggenerated
     */
    int deleteByExample(CNatureTreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnature_treat
     *
     * @mbggenerated
     */
    int insert(CNatureTreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnature_treat
     *
     * @mbggenerated
     */
    int insertSelective(CNatureTreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnature_treat
     *
     * @mbggenerated
     */
    List<CNatureTreat> selectByExample(CNatureTreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnature_treat
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CNatureTreat record, @Param("example") CNatureTreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnature_treat
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CNatureTreat record, @Param("example") CNatureTreatExample example);
}