package com.recommend_system.expandsalary.entity;

public class ExpandSalary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expandsalary.experience_min
     *
     * @mbggenerated
     */
    private Integer experienceMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expandsalary.experience_max
     *
     * @mbggenerated
     */
    private Integer experienceMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expandsalary.avg_salary
     *
     * @mbggenerated
     */
    private Integer avgSalary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expandsalary.experience_min
     *
     * @return the value of expandsalary.experience_min
     *
     * @mbggenerated
     */
    public Integer getExperienceMin() {
        return experienceMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expandsalary.experience_min
     *
     * @param experienceMin the value for expandsalary.experience_min
     *
     * @mbggenerated
     */
    public void setExperienceMin(Integer experienceMin) {
        this.experienceMin = experienceMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expandsalary.experience_max
     *
     * @return the value of expandsalary.experience_max
     *
     * @mbggenerated
     */
    public Integer getExperienceMax() {
        return experienceMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expandsalary.experience_max
     *
     * @param experienceMax the value for expandsalary.experience_max
     *
     * @mbggenerated
     */
    public void setExperienceMax(Integer experienceMax) {
        this.experienceMax = experienceMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expandsalary.avg_salary
     *
     * @return the value of expandsalary.avg_salary
     *
     * @mbggenerated
     */
    public Integer getAvgSalary() {
        return avgSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expandsalary.avg_salary
     *
     * @param avgSalary the value for expandsalary.avg_salary
     *
     * @mbggenerated
     */
    public void setAvgSalary(Integer avgSalary) {
        this.avgSalary = avgSalary;
    }
}