package com.recommend_system.cityneed.dao;

import com.recommend_system.cityneed.entity.CityNeed;
import com.recommend_system.cityneed.entity.CityNeedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CityNeedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityneed
     *
     * @mbggenerated
     */
    int countByExample(CityNeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityneed
     *
     * @mbggenerated
     */
    int deleteByExample(CityNeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityneed
     *
     * @mbggenerated
     */
    int insert(CityNeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityneed
     *
     * @mbggenerated
     */
    int insertSelective(CityNeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityneed
     *
     * @mbggenerated
     */
    List<CityNeed> selectByExample(CityNeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityneed
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CityNeed record, @Param("example") CityNeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cityneed
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CityNeed record, @Param("example") CityNeedExample example);
}