package com.recommend_system.cindustrytreat.dao;

import com.recommend_system.cindustrytreat.entity.CIndustryTreat;
import com.recommend_system.cindustrytreat.entity.CIndustryTreatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CIndustryTreatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    int countByExample(CIndustryTreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    int deleteByExample(CIndustryTreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    int insert(CIndustryTreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    int insertSelective(CIndustryTreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    List<CIndustryTreat> selectByExample(CIndustryTreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CIndustryTreat record, @Param("example") CIndustryTreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cindustry_treat
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CIndustryTreat record, @Param("example") CIndustryTreatExample example);
}